#!/bin/bash

# Define functions for each information required

# # ports
# ports(){

# }

# docker
docker(){
    echo "Docker Images:"
        docker images | column -t
        echo
        echo "Docker Containers:"
        docker ps -a | column -t
}

# # Nginx
# nginx(){

# }

# Users
users(){
    echo "Users and Last Login Times:"
    last | awk '!seen[$1]++ {print $1, $3, $4, $5, $6, $7}' | column -t
}

# # Time range
# time_range(){

# }

# Help
help(){
    echo """Usage: devopsfetch [OPTIONS]
    Your devops tool for server information retrieval and monitoring
    Global Options: 
        -p  --port    Display all active ports and services
                      Use -p <port_number> to get detailed information about a specific port 
        -d  --docker  List all Docker images and containers 
                      Use -d <container_name> to get detailed information about a specific container
        -n  --nginx   Display all Nginx domains and their ports
                      Use -n <domain> to get detailed configuration information for a specific domain
        -u  --users   List all users and their last login times
                      Use -u <username> ls
                      to get detailed information about a specific user
        -t  --time    Display activities within a specified time range
        -h  --help    Provide usage instructions for the program"""
}

# Process options when the devopsfetch is called
case "$1" in
        #  p | port) 
    
        #     ;;

        # -d | --docker) 
        #     docker "$2"
        #     ;;

        #  n | --nginx) 
    
        #     ;;

        -u|--users)
        users "$2"
            ;;

        # t | --time) 

        #     ;;
        
        -h|--help)
        help
        ;;
        # \?)
        #     echo "Invalid options"
        #     help
        #     ;;

esac
